### ISSUE TITLE
Not share node in Rete Network

### ISSUE THREAD

**Issue by DucVuMinh** [project-flogo/rules#103]
I fork your code and try to use it. When I create some Rules which have the same operator. But when I ran, I saw the repeat in the calculation

I used the examples/rulesapp
Here is my config for ruelsapp.json:
`[
  {
    "name": "n1",
    "properties": [
      {
        "name": "name",
        "type": "string",
        "pk-index": 0
      },
      {
        "name": "age",
        "type": "number",
        "pk-index": 1
      },
      {
        "name": "address",
        "type": "string",
        "pk-index": 2
      }
    ]
  },
  {
    "name": "n2",
    "properties": [
      {
        "name": "name",
        "type": "string",
        "pk-index": 0
      },
      {
        "name": "wife_name",
        "type": "string",
        "pk-index": 1
      },
      {
        "name": "child_name",
        "type": "string",
        "pk-index": 2
      }
    ]
  }
]`

Here is main function
[https://github.com/DucVuMinh/rules/blob/chech_rete_work/examples/rulesapp/main.go](url)

**Comment by rameshpolishetti** [comment]
@DucVuMinh mentioned calculations are repeated because the same condition function `checkForBob` added to both `rule` & `rule2`.

Use below like code snippet to understand the behavior:
`rule2.AddCondition("c1", []string{"n1"}, **checkForBob2**, nil)` //update print statements of checkForBob2 to distinguish from checkForBob 
`rule2.AddCondition("c1.1", []string{"n1"}, **checkAge2**, nil)`

**Comment by DucVuMinh** [comment]
@rameshpolishetti how i can use share node. Can you give me a example
