### ISSUE TITLE
Actions/Conditions Ignored if tuple is changed in an Action

### ISSUE THREAD

**Issue by nareshkumarthota** [project-flogo/rules#54]
**Current behavior (how does the issue manifest):**
Consider we have conditions c1,c2,c3 which are always true and corresponding actions a1,a2,a3. In a1 if we try to modify tuple value then a2 & a3 are not getting executed.

**Expected behavior:**
All actions a1,a2,a3 should get executed as c1,c2,c3 are always true.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Attached rule descriptor and main.go.
Run main.go file and see the output. Repeat the same by commenting line 72,73 you can see the difference.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
running with latest code taken from github.

**Flogo Rules version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

[issue.zip](https://github.com/project-flogo/rules/files/3230744/issue.zip)

**Comment by balamg** [comment]
Can you send the attachments? Even better, can you include a test case?

**Comment by nareshkumarthota** [comment]
hi @balamg. files attached, Run main.go file and see the output. Repeat the same by commenting line 72,73 you can see the difference.

**Comment by ssubrama-tibco** [comment]
Bala,
Abhay has built a go client for tgdb. Please work with him to built a Store
implementation for Rules

Sent from my iPhone

On Jun 7, 2019, at 3:00 AM, balamg <notifications@github.com> wrote:

Closed #54 <https://github.com/project-flogo/rules/issues/54>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/project-flogo/rules/issues/54?email_source=notifications&email_token=AESTIKDB4WP6IXO2CLK55SLPZIWTTA5CNFSM4HQDWI5KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOR3OG4XY#event-2396810847>,
or mute the thread
